package com.consilens.ai.tool;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import lombok.extern.slf4j.Slf4j;

/**
 * Tool that generates a Consilens YAML configuration file for a given pair of database tables.
 */
@Slf4j
public class ConfigGenerateTool implements Tool {

    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();

    @Override
    public String getName() {
        return "consilens_config_generate";
    }

    @Override
    public String getDescription() {
        return "Generates a Consilens YAML configuration file for comparing two database tables";
    }

    @Override
    public JsonNode getInputSchema() {
        ObjectNode schema = OBJECT_MAPPER.createObjectNode();
        schema.put("type", "object");
        ObjectNode props = schema.putObject("properties");
        props.putObject("source_url").put("type", "string").put("description", "Source JDBC URL");
        props.putObject("source_username").put("type", "string").put("description", "Source DB username");
        props.putObject("source_table").put("type", "string").put("description", "Source table name (schema.table)");
        props.putObject("target_url").put("type", "string").put("description", "Target JDBC URL");
        props.putObject("target_username").put("type", "string").put("description", "Target DB username");
        props.putObject("target_table").put("type", "string").put("description", "Target table name (schema.table)");
        props.putObject("primary_keys").put("type", "string").put("description", "Comma-separated primary key columns");
        props.putObject("compare_columns").put("type", "string").put("description", "Comma-separated columns to compare (optional, defaults to all)");
        schema.putArray("required").add("source_url").add("source_username").add("source_table")
                .add("target_url").add("target_username").add("target_table").add("primary_keys");
        return schema;
    }

    @Override
    public boolean isReadOnly() {
        return true;
    }

    @Override
    public ToolResult execute(JsonNode input, ToolContext context) {
        String sourceUrl = input.path("source_url").asText();
        String sourceUsername = input.path("source_username").asText();
        String sourceTable = input.path("source_table").asText();
        String targetUrl = input.path("target_url").asText();
        String targetUsername = input.path("target_username").asText();
        String targetTable = input.path("target_table").asText();
        String primaryKeys = input.path("primary_keys").asText();
        String compareColumns = input.path("compare_columns").asText(null);

        if (sourceUrl.isEmpty() || targetUrl.isEmpty() || sourceTable.isEmpty() || primaryKeys.isEmpty()) {
            return ToolResult.failure("Required parameters: source_url, source_username, source_table, target_url, target_username, target_table, primary_keys");
        }

        String yaml = buildYaml(sourceUrl, sourceUsername, sourceTable,
                targetUrl, targetUsername, targetTable, primaryKeys, compareColumns);

        return ToolResult.success(
                "Generated configuration:\n\n```yaml\n" + yaml + "\n```",
                yaml
        );
    }

    private String buildYaml(String sourceUrl, String sourceUsername, String sourceTable,
                              String targetUrl, String targetUsername, String targetTable,
                              String primaryKeys, String compareColumns) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Consilens diff configuration\n");
        sb.append("# Generated by Consilens AI\n\n");

        sb.append("source:\n");
        sb.append("  url: \"").append(sourceUrl).append("\"\n");
        sb.append("  username: \"").append(sourceUsername).append("\"\n");
        sb.append("  password: \"${SOURCE_PASSWORD}\"\n\n");

        sb.append("target:\n");
        sb.append("  url: \"").append(targetUrl).append("\"\n");
        sb.append("  username: \"").append(targetUsername).append("\"\n");
        sb.append("  password: \"${TARGET_PASSWORD}\"\n\n");

        sb.append("comparisons:\n");
        sb.append("  - source_table: \"").append(sourceTable).append("\"\n");
        sb.append("    target_table: \"").append(targetTable).append("\"\n");
        sb.append("    primary_keys:\n");
        for (String pk : primaryKeys.split(",")) {
            sb.append("      - \"").append(pk.trim()).append("\"\n");
        }
        if (compareColumns != null && !compareColumns.isEmpty()) {
            sb.append("    compare_columns:\n");
            for (String col : compareColumns.split(",")) {
                sb.append("      - \"").append(col.trim()).append("\"\n");
            }
        }
        return sb.toString();
    }
}
